# Home Manager configuration for nogami on the hd work machine.
{ lib, pkgs, ... }:

{
  imports = [ ./input-method/home-manager.nix ];

  home = {
    username = "nogami";
    homeDirectory = "/home/nogami";
    stateVersion = "26.05";

    pointerCursor = {
      gtk.enable = true;
      x11.enable = true;
      package = pkgs.bibata-cursors;
      name = "Bibata-Modern-Ice";
      size = 24;
    };

    sessionVariables = {
      #GTK_IM_MODULE = "fcitx";
      QT_IM_MODULE = "fcitx";
      XMODIFIERS = "@im=fcitx";
      SDL_IM_MODULE = "fcitx";
      GLFW_IM_MODULE = "ibus";
      MOZ_ENABLE_WAYLAND = "1";
    };
  };

  # Keep the user's existing functions and aliases editable, while restoring
  # NixOS's standard coloured prompt, dircolors and shell completion.
  home.file.".bashrc".text = ''
    if [[ -f /etc/bashrc ]]; then
      source /etc/bashrc
    fi

    if [[ -f "$HOME/.bashrc.local" ]]; then
      source "$HOME/.bashrc.local"
    fi
  '';

  xdg.enable = true;

  programs.noctalia = {
    enable = true;

    # Hyprland owns startup so there is exactly one Noctalia process per
    # graphical session. GUI experiments remain runtime overrides until the
    # merged user configuration is exported back to this repository.
    systemd.enable = false;
    settings = ./desktop/noctalia.toml;
  };

  # Plasma normally connects the SDDM PAM helper to KWallet during session
  # startup. Do the equivalent after the UWSM Hyprland environment is ready,
  # allowing the login password to unlock the wallet without another prompt.
  systemd.user.services.kwallet-pam-init = {
    Unit = {
      Description = "Unlock KWallet through the SDDM PAM socket";
      PartOf = [ "graphical-session.target" ];
      After = [ "wayland-session@hyprland.desktop.target" ];
      ConditionPathExists = "%t/kwallet5.socket";
    };

    Service = {
      Type = "oneshot";
      ExecStart = "${pkgs.coreutils}/bin/env PAM_KWALLET5_LOGIN=%t/kwallet5.socket ${pkgs.kdePackages.kwallet-pam}/libexec/pam_kwallet_init";
      RemainAfterExit = true;
    };

    Install.WantedBy = [ "wayland-session-xdg-autostart@hyprland.desktop.target" ];
  };

  gtk = {
    enable = true;

    # Plasma may replace Home Manager's GTK 2 symlink with a regular file.
    # Reclaim this generated file directly so an existing .hm-backup does not
    # block later activations.
    gtk2.force = true;

    theme = {
      package = pkgs.gnome-themes-extra;
      name = "Adwaita-dark";
    };
    iconTheme = {
      package = pkgs.papirus-icon-theme;
      name = "Papirus-Dark";
    };
    font = {
      name = "Noto Sans CJK SC";
      size = 11;
    };
  };

  xdg.configFile = {
    "hypr/hyprland.lua".source = ./desktop/hyprland.lua;

    # UWSM otherwise derives "hyprland-" from XDG_CURRENT_DESKTOP, but no
    # hyprland-applications.menu exists. Reuse Plasma's installed XDG menu so
    # KDE applications such as Dolphin can resolve desktop-file launchers.
    #
    # Plasma also exposes kde-gtk-config's colorreload module through the
    # system GTK_PATH. The module's file-monitor callback crashes unrelated
    # GTK3 processes when kded is first activated inside Hyprland. Hyprland
    # uses Home Manager's GTK theme and native Wayland input, so it does not
    # need the external Plasma/Fcitx GTK module search path.
    "uwsm/env-hyprland".text = ''
      export XDG_MENU_PREFIX=plasma-
      export GTK_PATH=
    '';
  };

  # A running Hyprland session may recreate a default hyprland.conf when the
  # old managed file disappears. Move that stub aside so the repo-owned Lua
  # configuration remains the only active compositor configuration.
  home.activation.disableAutogeneratedHyprlandConf = lib.hm.dag.entryBefore [ "checkLinkTargets" ] ''
    legacy_config="$HOME/.config/hypr/hyprland.conf"
    if [[ -f "$legacy_config" && ! -L "$legacy_config" ]]; then
      if grep -q '^autogenerated = 1$' "$legacy_config"; then
        run mv --backup=numbered "$legacy_config" "$legacy_config.autogenerated-disabled"
      fi
    fi
  '';

  home.activation.preserveUserBashrc = lib.hm.dag.entryBefore [ "checkLinkTargets" ] ''
    current_bashrc="$HOME/.bashrc"
    local_bashrc="$HOME/.bashrc.local"

    if [[ -f "$current_bashrc" && ! -L "$current_bashrc" && ! -e "$local_bashrc" ]]; then
      run mv "$current_bashrc" "$local_bashrc"
    fi
  '';

  programs.home-manager.enable = true;
}
